Make sure that sc after failure sc fails
riscv/riscv-tests pull request #465
Opened 2023-04-06 08:31 UTC by mohanson

Regardless of success or failure, executing an SC.W instruction invalidates any reservation held by this hart. So sc after failure sc must fails.

2023-04-06 16:55 UTC, aswaterman requested changes
This test doesn't work.  It gets stuck in an infinite loop when executed on Spike because the first SC is to a different address than the LR.

2023-04-07 02:00 UTC, mohanson commented
I mistakenly used an old `lrsc` binary for testing. I have fixed this.

2023-04-07 04:41 UTC, aswaterman commented
I don't think this version is correct, either, even though it now passes on Spike.  The problem is that implementations are allowed to reserve more than one word of memory on an LR, so the SC might succeed on some implementations even though the addresses differ.

I made a version of this that does work in general, by piggy-backing on the previous test, which does contain an SC that we know will fail by construction.  https://github.com/riscv-software-src/riscv-tests/commit/394937eceb62bc4ba8ad5a4e916f0508d9803229

2023-04-07 05:38 UTC, mohanson commented
Your version is better, this PR no longer needs to open.

2023-04-07 05:38 UTC, closed without merging